include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.default.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.rules.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.scripts.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.variables.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.workflow.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/build.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/test.windows.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/quality.yml

default:
  image: mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019
  tags:
    - rt-windows

stages:
  - build
  - test
  - quality
  - package
  - package-test
  - sign

variables:
  PACKAGE_NAME_EXE: Reductech.EDR
  NUGET_XMLDOC_MODE: none
  CONNECTORS_JSON: ./lib/connectors.json

.exe_artifacts_default:
  artifacts:
    name: '$PACKAGE_NAME_EXE-$PROJECT_VERSION'
    paths:
      - lib/
      - CHANGELOG.md
      - edr.exe
      - LICENSE
      - README.md

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG --collect:"XPlat Code Coverage" --results-directory ./
      -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.UseSourceLink=true
    - |
      $report = Get-Content -Path "*/coverage.cobertura.xml" -Raw ;
      $fixPaths = $report -replace "filename=`".+?edr(/|\\)edr(/|\\)", "filename=`"" ;
      $fixPaths = $fixPaths -replace '\\', '/' ;
      $outPath = Join-Path (Get-Location) "coverage.$($env:CI_JOB_NAME -replace "[^\w]+", "-").xml" ;
      [System.IO.File]::WriteAllText($outPath, $fixPaths) ;

package exe dev:
  stage: package
  extends:
    - .rules_dev_manual
    - .exe_artifacts_default
  needs:
    - build dev
    - test dev
    - version check dev
  script:
    - dotnet publish --no-build --configuration $CONFIG_DEV --output ./lib
      --version-suffix $VERSION_SUFFIX
    - ./single-fileish.ps1
  artifacts:
    expire_in: 3 months

package exe release:
  stage: package
  extends:
    - .rules_release
    - .exe_artifacts_default
  needs:
    - build release
    - test release
    - version check release
  script:
    - dotnet publish --no-build --configuration $CONFIG_RELEASE --output ./lib
    - ./single-fileish.ps1
  artifacts:
    expire_in: 2 hours

# Test the package
test package dev:
  stage: package-test
  cache: {}
  extends:
    - .rules_dev_manual
  needs:
    - package exe dev
  before_script:
    - .\edr.exe connector add --force --prerelease Reductech.EDR.Connectors.FileSystem
    - .\edr.exe connector add --force --prerelease Reductech.EDR.Connectors.StructuredData
    - .\edr.exe connector add --prerelease Reductech.EDR.Connectors.Pwsh
  script:
    - .\edr.exe run .\Examples\core-sequence.scl
    - .\edr.exe run .\Examples\pwsh-sequence.scl
    - .\edr.exe run .\Examples\doc-generation.scl

test package release:
  extends:
    - test package dev
    - .rules_release
  needs:
    - package exe release
  before_script:
    - .\edr.exe connector add --force Reductech.EDR.Connectors.FileSystem
    - .\edr.exe connector add --force Reductech.EDR.Connectors.StructuredData
    - .\edr.exe connector add Reductech.EDR.Connectors.Pwsh

# Test the Nuix connector
test package dev nuix:
  tags:
    - nuix
  extends:
    - test package dev
  variables:
    PRERELEASE_FLAG: --prerelease
  before_script:
    - |
      $config = Get-Content $env:CONNECTORS_JSON -Raw | ConvertFrom-Json ;
      $config | Add-Member -NotePropertyName "Reductech.EDR.Connectors.Nuix" -NotePropertyValue @{
          id      = "Reductech.EDR.Connectors.Nuix"
          version = "0.11.0"
          settings = @{
            exeConsolePath = "C:\Program Files\Nuix\Nuix 9.0\nuix_console.exe"
            licencesourcetype = "dongle"
            version = "9.0"
            features = @(
              "ANALYSIS"
              "CASE_CREATION"
              "EXPORT_ITEMS"
              "METADATA_IMPORT"
              "OCR_PROCESSING"
              "PRODUCTION_SET"
            )
          }
      } ;
      $config | ConvertTo-Json -Depth 100 | Out-File $env:CONNECTORS_JSON -Encoding utf8NoBOM ;
    - .\edr.exe connector update $PRERELEASE_FLAG Reductech.EDR.Connectors.FileSystem
    - .\edr.exe connector update $PRERELEASE_FLAG Reductech.EDR.Connectors.StructuredData
    - .\edr.exe connector update $PRERELEASE_FLAG Reductech.EDR.Connectors.Nuix
    - .\edr.exe connector list
  script:
    - .\edr.exe run .\Examples\nuix-sequence.scl

test package release nuix:
  extends:
    - test package dev nuix
    - .rules_release
  needs:
    - package exe release
  variables:
    PRERELEASE_FLAG: ''

# Test SQL Connector
test package dev sql:
  variables:
    INIT_DATABASE: TestDb
    SA_PASSWORD: T35tDbPa5s
  services:
    - name: registry.gitlab.com/reductech/containers/sqlserver:latest
      alias: sqlserver
  extends:
    - test package dev
  before_script:
    - .\edr.exe connector add --force --prerelease Reductech.EDR.Connectors.FileSystem
    - .\edr.exe connector add --force --prerelease Reductech.EDR.Connectors.StructuredData
    - .\edr.exe connector add --prerelease Reductech.EDR.Connectors.Sql
  script:
    - .\edr.exe run .\Examples\sql-sequence.scl

test package release sql:
  extends:
    - test package dev sql
    - .rules_release
  needs:
    - package exe release
  before_script:
    - .\edr.exe connector add --force Reductech.EDR.Connectors.FileSystem
    - .\edr.exe connector add --force Reductech.EDR.Connectors.StructuredData
    - .\edr.exe connector add Reductech.EDR.Connectors.Sql

# Test Tesseract Connector
test package dev tesseract:
  image: registry.gitlab.com/reductech/containers/msvc
  extends:
    - test package dev
  before_script:
    - .\edr.exe connector add --force --prerelease Reductech.EDR.Connectors.FileSystem
    - .\edr.exe connector add --force --prerelease Reductech.EDR.Connectors.StructuredData
    - .\edr.exe connector add Reductech.EDR.Connectors.Tesseract --prerelease
  script:
    - .\edr.exe run .\Examples\tesseract-sequence.scl

test package release tesseract:
  extends:
    - test package dev tesseract
    - .rules_release
  needs:
    - package exe release

# Test the Relativity connector
test package dev relativity:
  tags:
    - nuix
  extends:
    - test package dev
  variables:
    PRERELEASE_FLAG: --prerelease
  before_script:
    - |
      $config = Get-Content $env:CONNECTORS_JSON -Raw | ConvertFrom-Json ;
      $config | Add-Member -NotePropertyName "Reductech.EDR.Connectors.Relativity" -NotePropertyValue @{
          id      = "Reductech.EDR.Connectors.Relativity"
          version = "0.11.0"
          settings = @{
            RelativityUsername = $env:RELATIVITY_TEST_USER
            RelativityPassword = $env:RELATIVITY_TEST_PASS
            Url = $env:RELATIVITY_TEST_URL
          }
      } ;
      $config | ConvertTo-Json -Depth 100 | Out-File $env:CONNECTORS_JSON -Encoding utf8NoBOM ;
    - .\edr.exe connector update $PRERELEASE_FLAG Reductech.EDR.Connectors.FileSystem
    - .\edr.exe connector update $PRERELEASE_FLAG Reductech.EDR.Connectors.StructuredData
    - .\edr.exe connector update $PRERELEASE_FLAG Reductech.EDR.Connectors.Relativity
    - .\edr.exe connector list
  script:
    - .\edr.exe run .\Examples\relativity-sequence.scl

test package release relativity:
  extends:
    - test package dev relativity
    - .rules_release_allowfailure
  needs:
    - package exe release
  variables:
    PRERELEASE_FLAG: ''

sign exe release:
  stage: sign
  image: registry.gitlab.com/reductech/containers/codesigning
  cache: {}
  extends:
    - .rules_release
    - .exe_artifacts_default
  needs:
    - version check release
    - package exe release
    - test package release
  variables:
    TIMESTAMP_SERVER: http://timestamp.sectigo.com
    ALGO_FILE_DIGEST: SHA256
    ALGO_TIME_DIGEST: SHA256
  script:
    - signtool.exe sign /f $RT_CERT_PATH /p $RT_CERT_PASS /fd $ALGO_FILE_DIGEST
      /tr $TIMESTAMP_SERVER /td $ALGO_TIME_DIGEST .\edr.exe
    - signtool.exe sign /f $RT_CERT_PATH /p $RT_CERT_PASS /fd $ALGO_FILE_DIGEST
      /tr $TIMESTAMP_SERVER /td $ALGO_TIME_DIGEST .\lib\edr.exe
  artifacts:
    expire_in: never

code_quality:
  tags:
    - rt-dind

code coverage dev:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - rt-linux

code coverage release:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - rt-linux
