include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.default.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.rules.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.scripts.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.variables.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.workflow.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/build.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/test.windows.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/quality.yml

default:
  image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019
  tags:
    - rt-windows

stages:
  - build
  - test
  - quality
  - package
  - package-test
  - sign

variables:
  PACKAGE_NAME_EXE: Reductech.Sequence
  NUGET_XMLDOC_MODE: none

.exe_artifacts_default:
  artifacts:
    name: '$PACKAGE_NAME_EXE-$PROJECT_VERSION'
    paths:
      - lib/
      - CHANGELOG.md
      - sequence.exe
      - LICENSE
      - README.md

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG --collect:"XPlat Code Coverage" --results-directory ./
      -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.UseSourceLink=true
    - |
      $report = Get-Content -Path "*/coverage.cobertura.xml" -Raw ;
      $fixPaths = $report -replace "filename=`".+?edr(/|\\)edr(/|\\)", "filename=`"" ;
      $fixPaths = $fixPaths -replace '\\', '/' ;
      $outPath = Join-Path (Get-Location) "coverage.$($env:CI_JOB_NAME -replace "[^\w]+", "-").xml" ;
      [System.IO.File]::WriteAllText($outPath, $fixPaths) ;

package exe dev:
  stage: package
  extends:
    - .rules_dev
    - .exe_artifacts_default
  needs:
    - build dev
    - test dev
    - version check dev
  script:
    - dotnet publish --no-build --configuration $CONFIG_DEV --output ./lib
      --version-suffix $VERSION_SUFFIX
    - ./single-fileish.ps1
  artifacts:
    expire_in: 3 months

package exe release:
  stage: package
  extends:
    - .rules_release
    - .exe_artifacts_default
  needs:
    - build release
    - test release
    - version check release
  script:
    - dotnet publish --no-build --configuration $CONFIG_RELEASE --output ./lib
    - ./single-fileish.ps1
  artifacts:
    expire_in: 2 hours

test examples dev:
  stage: package-test
  extends:
    - .rules_dev
  needs:
    - package exe dev
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include: Examples/example-tests.yml
    strategy: depend

test examples release:
  extends:
    - test examples dev
    - .rules_release
  needs:
    - package exe release

sign exe release:
  stage: sign
  image: registry.gitlab.com/reductech/containers/codesigning
  cache: {}
  extends:
    - .rules_release
    - .exe_artifacts_default
  needs:
    - version check release
    - package exe release
    - test examples release
  variables:
    TIMESTAMP_SERVER: http://timestamp.sectigo.com
    ALGO_FILE_DIGEST: SHA256
    ALGO_TIME_DIGEST: SHA256
  script:
    - signtool.exe sign /f $RT_CERT_PATH /p $RT_CERT_PASS /fd $ALGO_FILE_DIGEST
      /tr $TIMESTAMP_SERVER /td $ALGO_TIME_DIGEST .\sequence.exe
    - signtool.exe sign /f $RT_CERT_PATH /p $RT_CERT_PASS /fd $ALGO_FILE_DIGEST
      /tr $TIMESTAMP_SERVER /td $ALGO_TIME_DIGEST .\lib\sequence.exe
  artifacts:
    expire_in: never

code_quality:
  tags: []

security-code-scan-sast:
  tags: []

secret_detection:
  tags: []

code coverage dev:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  tags: []

code coverage release:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  tags: []
