include:
  - project: sequence/templates/cicd
    file: .gitlab/ci/default.default.yml
  - project: sequence/templates/cicd
    file: .gitlab/ci/default.rules.yml
  - project: sequence/templates/cicd
    file: .gitlab/ci/default.workflow.yml

default:
  image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019
  tags:
    - rt-windows

stages:
  - package-test

variables:
  CONNECTORS_JSON: ./lib/connectors.json

test package dev:
  stage: package-test
  cache: {}
  extends:
    - .rules_dev
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: package exe dev
  script:
    - rm $env:CONNECTORS_JSON
    - .\sequence.exe run .\Examples\core-sequence.scl

test package release:
  extends:
    - test package dev
    - .rules_release
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: package exe release

test package connectors dev:
  extends:
    - test package dev
  variables:
    PRERELEASE_FLAG: --prerelease
  before_script:
    - .\sequence.exe connector update $PRERELEASE_FLAG Sequence.Connectors.FileSystem
    - .\sequence.exe connector update $PRERELEASE_FLAG Sequence.Connectors.StructuredData
    - .\sequence.exe connector add $PRERELEASE_FLAG Sequence.Connectors.Pwsh
  script:
    - .\sequence.exe run .\Examples\file-system-sequence.scl
    - .\sequence.exe run .\Examples\pwsh-sequence.scl
    - .\sequence.exe run .\Examples\doc-generation.scl

test package connectors release:
  extends:
    - test package connectors dev
    - .rules_release
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: package exe release
  variables:
    PRERELEASE_FLAG: ''

# Test SQL Connector
test package dev sql:
  extends:
    - test package dev
  variables:
    PRERELEASE_FLAG: --prerelease
    INIT_DATABASE: TestDb
    SA_PASSWORD: T35tDbPa5s
  services:
    - name: registry.gitlab.com/sequence/containers/sqlserver:latest
      alias: sqlserver
  before_script:
    - .\sequence.exe connector update $PRERELEASE_FLAG Sequence.Connectors.FileSystem
    - .\sequence.exe connector update $PRERELEASE_FLAG Sequence.Connectors.StructuredData
    - .\sequence.exe connector add $PRERELEASE_FLAG Sequence.Connectors.Sql
  script:
    - .\sequence.exe run .\Examples\sql-sequence.scl

test package release sql:
  extends:
    - test package dev sql
    - .rules_release
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: package exe release
  variables:
    PRERELEASE_FLAG: ''

# Test Tesseract Connector
test package dev tesseract:
  extends:
    - test package dev
  image: registry.gitlab.com/sequence/containers/msvc
  variables:
    PRERELEASE_FLAG: --prerelease
  before_script:
    - .\sequence.exe connector update $PRERELEASE_FLAG Sequence.Connectors.FileSystem
    - .\sequence.exe connector update $PRERELEASE_FLAG Sequence.Connectors.StructuredData
    - .\sequence.exe connector add --prerelease Sequence.Connectors.Tesseract
  script:
    - .\sequence.exe run .\Examples\tesseract-sequence.scl

test package release tesseract:
  extends:
    - test package dev tesseract
    - .rules_release
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: package exe release
  variables:
    PRERELEASE_FLAG: ''
